spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  webflux:
    base-path: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

yandex:
  storage:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ru-central1
    bucket-name: mmf-bsu-mag
